# Generated by Django 3.0.7 on 2020-06-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200627_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postDescriptions',
            field=models.TextField(default=11.11),
            preserve_default=False,
        ),
    ]
