# Generated by Django 3.0.7 on 2020-06-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_postdescriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title_without_space',
            field=models.CharField(default=11.11, max_length=200),
            preserve_default=False,
        ),
    ]
