# Generated by Django 3.0.7 on 2020-06-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
