# Generated by Django 3.0.7 on 2020-06-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200629_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=11.11, max_length=80),
            preserve_default=False,
        ),
    ]
