# Generated by Django 3.0.7 on 2020-06-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat_search',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category'), max_length=200),
        ),
    ]
