# Generated by Django 3.0.7 on 2020-06-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200630_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat_search',
            field=models.CharField(max_length=200),
        ),
    ]
